'use client'
import { useState } from 'react'
import { Blueprint } from '../types'

interface PRDGeneratorProps {
  blueprint: Blueprint
  idea: string
  onClose: () => void
}

export function PRDGenerator({ blueprint, idea, onClose }: PRDGeneratorProps) {
  const [generating, setGenerating] = useState(false)
  const [done, setDone] = useState(false)

  const generateAndDownload = async (format: 'markdown' | 'pdf') => {
    setGenerating(true)

    const b = blueprint
    const users = (b.users || [])
    const goals = (b.business_goals || [])
    const jtbds = (b.jobs_to_be_done || [])
    const features = (b.feature_breakdown || [])
    const services = (b.services || [])
    const entities = (b.domain_entities || [])
    const rules = (b.business_rules || [])
    const integrations = (b.integrations || [])
    const flows = (b.system_flow || [])

    if (format === 'markdown') {
      const lines = [
        `# Product Requirements Document`,
        `## ${idea}`,
        ``,
        `---`,
        ``,
        `## Executive Summary`,
        ``,
        b.prd_summary || '',
        ``,
        `---`,
        ``,
        `## Users`,
        ``,
        ...users.map(u => [
          `### ${u.name}`,
          `**Role:** ${u.role}`,
          ``,
          u.description,
          ``,
        ].join('\n')),
        `---`,
        ``,
        `## Business Goals`,
        ``,
        ...goals.map((g, i) => `${i + 1}. ${g}`),
        ``,
        `---`,
        ``,
        `## Jobs To Be Done`,
        ``,
        `> These are the core reasons users would hire this product.`,
        ``,
        ...jtbds.map((j, i) => `**${i + 1}.** ${j}`),
        ``,
        `---`,
        ``,
        `## Feature Breakdown`,
        ``,
        ...features.map(f => [
          `### ${f.feature} \`${f.badge}\``,
          `**Owned by:** ${f.service}`,
          ``,
          f.description,
          ``,
        ].join('\n')),
        `---`,
        ``,
        `## System Architecture`,
        ``,
        b.system_explanation || '',
        ``,
        ...services.map(s => [
          `### ${s.name}`,
          `**Group:** ${s.group}`,
          ``,
          s.description,
          ``,
          `**APIs:**`,
          ...(s.apis || []).map(a => `- \`${a.method} ${a.route}\` — ${a.purpose}`),
          ``,
          s.dependencies?.length ? `**Dependencies:** ${s.dependencies.join(', ')}` : '',
          ``,
        ].join('\n')),
        `---`,
        ``,
        `## Domain Entities`,
        ``,
        ...entities.map(e => [
          `### ${e.name}`,
          e.description,
          ``,
          `**Fields:** ${(e.fields || []).join(', ')}`,
          ``,
        ].join('\n')),
        `---`,
        ``,
        `## Business Rules`,
        ``,
        ...rules.map((r, i) => `${i + 1}. ${r}`),
        ``,
        `---`,
        ``,
        `## External Integrations`,
        ``,
        ...integrations.map(i => `- **${i.name}** — ${i.purpose}`),
        ``,
        `---`,
        ``,
        `## System Flow`,
        ``,
        ...flows.map(f => `**Step ${f.step}:** ${f.from} → ${f.to} — ${f.action}`),
        ``,
        `---`,
        ``,
        `## Data Layer`,
        ``,
        b.data_layer?.database ? `- **Database:** ${b.data_layer.database}` : '',
        b.data_layer?.cache ? `- **Cache:** ${b.data_layer.cache}` : '',
        b.data_layer?.storage ? `- **Storage:** ${b.data_layer.storage}` : '',
        ``,
        b.data_layer?.description || '',
        ``,
        `---`,
        ``,
        `*Generated by cornea.ai*`,
      ]

      const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `prd-${idea.slice(0, 30).replace(/\s+/g, '-').toLowerCase()}.md`
      a.click()
      URL.revokeObjectURL(url)
    }

    if (format === 'pdf') {
      const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>PRD — ${idea}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, 'Segoe UI', sans-serif; color: #1a1a2e; background: #fff; padding: 56px; max-width: 900px; margin: 0 auto; line-height: 1.7; }
  h1 { font-size: 32px; font-weight: 700; color: #0f1117; margin-bottom: 6px; }
  .subtitle { font-size: 16px; color: #666; margin-bottom: 40px; }
  h2 { font-size: 13px; font-weight: 700; color: #4a7cf0; text-transform: uppercase; letter-spacing: 0.1em; margin-top: 40px; margin-bottom: 14px; padding-bottom: 8px; border-bottom: 2px solid #eef3ff; }
  h3 { font-size: 15px; font-weight: 600; color: #1a1a2e; margin-top: 18px; margin-bottom: 6px; }
  p, li { font-size: 14px; color: #374151; }
  ul, ol { padding-left: 22px; margin: 8px 0; }
  li { margin-bottom: 5px; }
  .tag { display: inline-block; font-size: 11px; padding: 2px 10px; border-radius: 20px; background: #eef3ff; color: #4a7cf0; border: 1px solid #c5d8fc; margin-left: 6px; vertical-align: middle; font-weight: 600; }
  .tag.core { background: #eef3ff; color: #4a7cf0; border-color: #c5d8fc; }
  .tag.premium { background: #edfaf4; color: #0db882; border-color: #b8ecd8; }
  .tag.admin { background: #fff8ee; color: #e08020; border-color: #f5dec8; }
  .tag.system { background: #f0eeff; color: #7c5cf0; border-color: #d4cafc; }
  .user-card { background: #f8faff; border: 1px solid #e2eafc; border-radius: 12px; padding: 16px 18px; margin-bottom: 12px; }
  .user-name { font-size: 15px; font-weight: 600; color: #4a7cf0; }
  .user-role { font-size: 12px; color: #888; margin-bottom: 6px; }
  .feat-card { background: #fafafa; border: 1px solid #eee; border-radius: 10px; padding: 14px 16px; margin-bottom: 10px; }
  .feat-name { font-size: 14px; font-weight: 600; display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
  .service-card { background: #f8f5ff; border: 1px solid #e0d8fc; border-radius: 10px; padding: 14px 16px; margin-bottom: 12px; }
  .service-name { font-size: 14px; font-weight: 700; color: #7c5cf0; margin-bottom: 4px; }
  .service-group { font-size: 11px; color: #a88cf8; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 8px; }
  .api { font-family: monospace; font-size: 12px; padding: 5px 10px; background: #f0eeff; border-radius: 6px; margin: 3px 0; display: block; }
  .api-method { font-weight: 700; margin-right: 8px; }
  .api-method.get { color: #0db882; }
  .api-method.post { color: #4a7cf0; }
  .api-method.put, .api-method.patch { color: #e08020; }
  .api-method.delete { color: #e05050; }
  .entity-card { background: #edfaf4; border: 1px solid #b8ecd8; border-radius: 10px; padding: 14px 16px; margin-bottom: 10px; }
  .entity-name { font-size: 14px; font-weight: 600; color: #0db882; margin-bottom: 4px; }
  .fields { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 8px; }
  .field { font-family: monospace; font-size: 11px; padding: 2px 8px; background: rgba(13,184,130,0.1); border-radius: 4px; color: #0a9e70; }
  .rule { background: #fff8ee; border: 1px solid #f5dec8; border-radius: 8px; padding: 10px 14px; margin-bottom: 8px; font-size: 13px; color: #8a4a00; }
  .integration { display: inline-flex; align-items: center; gap: 6px; background: #f8f0ff; border: 1px solid #e0c8f8; border-radius: 8px; padding: 6px 12px; margin: 4px; font-size: 13px; color: #7040b0; }
  .flow-step { display: flex; gap: 14px; margin-bottom: 12px; }
  .step-num { width: 28px; height: 28px; border-radius: 50%; background: #eef3ff; color: #4a7cf0; font-weight: 700; font-size: 13px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
  .step-content { flex: 1; }
  .step-route { font-size: 13px; font-weight: 600; color: #1a1a2e; margin-bottom: 2px; }
  .step-action { font-size: 12px; color: #666; }
  .data-item { display: flex; justify-content: space-between; padding: 10px 16px; background: #edfaf4; border: 1px solid #b8ecd8; border-radius: 8px; margin-bottom: 8px; }
  .footer { margin-top: 56px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #aaa; text-align: center; }
  .jtbd-item { background: #f8faff; border-left: 3px solid #4a7cf0; padding: 10px 14px; margin-bottom: 8px; border-radius: 0 8px 8px 0; font-size: 13px; color: #374151; }
  .summary { font-size: 15px; line-height: 1.8; color: #374151; background: #f8faff; padding: 20px; border-radius: 12px; border: 1px solid #e2eafc; }
  @media print { body { padding: 32px; } }
</style>
</head>
<body>

<h1>Product Requirements Document</h1>
<div class="subtitle">${idea}</div>

<h2>Executive Summary</h2>
<div class="summary">${b.prd_summary || ''}</div>

<h2>Users (${users.length})</h2>
${users.map(u => `
<div class="user-card">
  <div class="user-name">${u.name}</div>
  <div class="user-role">${u.role}</div>
  <p>${u.description}</p>
</div>`).join('')}

<h2>Business Goals</h2>
<ol>${goals.map(g => `<li>${g}</li>`).join('')}</ol>

<h2>Jobs To Be Done</h2>
${jtbds.map(j => `<div class="jtbd-item">${j}</div>`).join('')}

<h2>Feature Breakdown</h2>
${features.map(f => {
  const badgeClass = f.badge?.toLowerCase() || 'core'
  return `
<div class="feat-card">
  <div class="feat-name">${f.feature} <span class="tag ${badgeClass}">${f.badge}</span></div>
  <p style="margin-bottom:6px">${f.description}</p>
  <small style="color:#888">Owned by: ${f.service}</small>
</div>`
}).join('')}

<h2>System Architecture</h2>
<div class="summary" style="margin-bottom:20px">${b.system_explanation || ''}</div>
${services.map(s => `
<div class="service-card">
  <div class="service-name">${s.name}</div>
  <div class="service-group">${s.group}</div>
  <p style="margin-bottom:10px">${s.description}</p>
  ${(s.apis||[]).map(a => `<code class="api"><span class="api-method ${a.method.toLowerCase()}">${a.method}</span> ${a.route} — ${a.purpose}</code>`).join('')}
  ${s.dependencies?.length ? `<p style="margin-top:10px;font-size:12px;color:#888"><strong>Dependencies:</strong> ${s.dependencies.join(', ')}</p>` : ''}
</div>`).join('')}

<h2>Domain Entities</h2>
${entities.map(e => `
<div class="entity-card">
  <div class="entity-name">${e.name}</div>
  <p>${e.description}</p>
  <div class="fields">${(e.fields||[]).map(f => `<span class="field">${f}</span>`).join('')}</div>
</div>`).join('')}

<h2>Business Rules</h2>
${rules.map(r => `<div class="rule">${r}</div>`).join('')}

<h2>External Integrations</h2>
<div>${integrations.map(i => `<span class="integration">🔗 <strong>${i.name}</strong> — ${i.purpose}</span>`).join('')}</div>

<h2>System Flow</h2>
${flows.map(f => `
<div class="flow-step">
  <div class="step-num">${f.step}</div>
  <div class="step-content">
    <div class="step-route">${f.from} → ${f.to}</div>
    <div class="step-action">${f.action}</div>
  </div>
</div>`).join('')}

<h2>Data Layer</h2>
${[
  { label: 'Database', value: b.data_layer?.database },
  { label: 'Cache', value: b.data_layer?.cache },
  { label: 'Storage', value: b.data_layer?.storage },
].filter(d => d.value).map(d => `<div class="data-item"><span>${d.label}</span><strong>${d.value}</strong></div>`).join('')}
<p style="margin-top:10px;font-size:13px;color:#666">${b.data_layer?.description || ''}</p>

<div class="footer">Generated by cornea.ai</div>
</body></html>`

      const blob = new Blob([html], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      const win = window.open(url, '_blank')
      if (win) win.onload = () => setTimeout(() => { win.print(); URL.revokeObjectURL(url) }, 500)
    }

    setGenerating(false)
    setDone(true)
    setTimeout(() => setDone(false), 2000)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ background: 'rgba(5,5,15,0.85)', backdropFilter: 'blur(8px)' }}>
      <div className="w-full max-w-[480px] mx-4 rounded-2xl overflow-hidden"
        style={{ background: '#0a0a1a', border: '1px solid rgba(255,255,255,0.1)', boxShadow: '0 24px 64px rgba(0,0,0,0.6)' }}>

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-5"
          style={{ borderBottom: '1px solid rgba(255,255,255,0.07)' }}>
          <div>
            <h3 className="text-[16px] font-semibold" style={{ color: 'rgba(255,255,255,0.92)' }}>Generate PRD</h3>
            <p className="text-[12px] mt-0.5" style={{ color: 'rgba(255,255,255,0.35)' }}>
              Full product requirements document
            </p>
          </div>
          <button onClick={onClose}
            className="w-7 h-7 rounded-lg flex items-center justify-center transition-opacity hover:opacity-60"
            style={{ background: 'rgba(255,255,255,0.06)', color: 'rgba(255,255,255,0.4)', fontSize: 13 }}>
            ✕
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-5">
          <p className="text-[13px] leading-relaxed mb-6" style={{ color: 'rgba(255,255,255,0.45)' }}>
            This generates a detailed PRD with all users, JTBDs, features, architecture, APIs, domain entities, business rules, and system flow — ready to share with your team or use with AI coding tools.
          </p>

          {/* What's included */}
          <div className="rounded-xl p-4 mb-6"
            style={{ background: 'rgba(74,124,240,0.07)', border: '1px solid rgba(74,124,240,0.18)' }}>
            <p className="text-[11px] uppercase tracking-widest mb-3 font-semibold" style={{ color: 'rgba(74,124,240,0.7)' }}>
              Includes
            </p>
            <div className="grid grid-cols-2 gap-1.5">
              {['Executive summary', 'All user types', 'Business goals', 'Jobs to be done',
                'Feature breakdown', 'System architecture', 'API endpoints', 'Domain entities',
                'Business rules', 'System flow', 'Data layer', 'Integrations'].map((item, i) => (
                <div key={i} className="flex items-center gap-2">
                  <span style={{ color: '#3dd4a0', fontSize: 11 }}>✓</span>
                  <span className="text-[12px]" style={{ color: 'rgba(255,255,255,0.5)' }}>{item}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Download buttons */}
          <div className="flex gap-3">
            <button
              onClick={() => generateAndDownload('markdown')}
              disabled={generating}
              className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-[14px] font-medium transition-all"
              style={{
                background: 'rgba(255,255,255,0.06)',
                border: '1px solid rgba(255,255,255,0.12)',
                color: done ? '#3dd4a0' : 'rgba(255,255,255,0.75)',
              }}>
              {generating ? '⏳' : done ? '✓' : '📄'} Markdown
            </button>
            <button
              onClick={() => generateAndDownload('pdf')}
              disabled={generating}
              className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-[14px] font-medium transition-all btn-primary"
              style={{ opacity: generating ? 0.6 : 1 }}>
              {generating ? '⏳ Generating...' : done ? '✓ Done!' : '📑 PDF'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
