import jsPDF from 'jspdf'
import { Blueprint } from '../types'

const BLUE = '#1a56db'
const INK = '#0a0e1a'
const INK2 = '#374151'
const INK3 = '#6b7280'
const INK4 = '#9ca3af'
const RULE = '#e5e7eb'
const BG2 = '#f9fafb'
const GREEN = '#047857'
const AMBER = '#b45309'
const PURPLE = '#6d28d9'
const RED = '#b91c1c'

const METHOD_COLORS: Record<string, string> = {
  GET: GREEN, POST: BLUE, PUT: AMBER, PATCH: AMBER, DELETE: RED,
}
const BADGE_COLORS: Record<string, string> = {
  Core: BLUE, Premium: GREEN, Admin: AMBER, System: PURPLE,
}

export async function generatePRDPdf(blueprint: Blueprint, idea: string): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = 210
  const M = 20
  const CW = W - M * 2
  let y = 0

  const addPage = () => { doc.addPage(); y = M }
  const checkY = (needed: number) => { if (y + needed > 272) addPage() }

  const sf = (size: number, style: 'normal' | 'bold' = 'normal', color = INK) => {
    doc.setFontSize(size); doc.setFont('helvetica', style); doc.setTextColor(color)
  }
  const fillRect = (x: number, ry: number, w: number, h: number, fill: string, r = 0) => {
    doc.setFillColor(fill); doc.setDrawColor(fill)
    r > 0 ? doc.roundedRect(x, ry, w, h, r, r, 'F') : doc.rect(x, ry, w, h, 'F')
  }
  const strokeRect = (x: number, ry: number, w: number, h: number, fill: string, stroke: string, r = 0) => {
    doc.setFillColor(fill); doc.setDrawColor(stroke); doc.setLineWidth(0.3)
    r > 0 ? doc.roundedRect(x, ry, w, h, r, r, 'FD') : doc.rect(x, ry, w, h, 'FD')
  }
  const hline = (ly: number, color = RULE) => {
    doc.setDrawColor(color); doc.setLineWidth(0.25); doc.line(M, ly, W - M, ly)
  }
  const tx = (str: string, x: number, ty: number, opts?: any) => doc.text(str, x, ty, opts)

  const secHeader = (num: string, title: string) => {
    checkY(16)
    fillRect(M, y - 4, 7, 7, BLUE, 1.5)
    sf(8, 'bold', '#ffffff'); tx(num, M + 1.5, y + 0.5)
    sf(13, 'bold', INK); tx(title, M + 10, y + 0.5)
    y += 5; hline(y, '#d1d5db'); y += 8
  }

  const badgeTag = (label: string, x: number, ty: number, color: string) => {
    const tw = doc.getTextWidth(label) + 6
    doc.setFillColor(color + '28'); doc.setDrawColor(color + '55'); doc.setLineWidth(0.3)
    doc.roundedRect(x, ty - 3.5, tw, 5.5, 1.5, 1.5, 'FD')
    sf(8, 'bold', color); tx(label, x + 3, ty + 0.5)
    return tw + 3
  }

  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  // ── COVER ─────────────────────────────────────────────────────────
  doc.setFillColor(BLUE); doc.rect(0, 0, W * 0.34, 5, 'F')
  doc.setFillColor(PURPLE); doc.rect(W * 0.34, 0, W * 0.33, 5, 'F')
  doc.setFillColor(GREEN); doc.rect(W * 0.67, 0, W * 0.33, 5, 'F')

  y = 38
  sf(9, 'bold', BLUE); tx('PRODUCT REQUIREMENTS DOCUMENT', M, y); y += 14
  sf(28, 'bold', INK)
  const tLines = doc.splitTextToSize(idea, CW)
  tLines.forEach((l: string) => { tx(l, M, y); y += 11 }); y += 4
  fillRect(M, y, 14, 1.5, BLUE, 1); y += 10
  sf(11, 'normal', INK2)
  doc.splitTextToSize(blueprint.prd_summary || '', CW).slice(0, 4).forEach((l: string) => { tx(l, M, y); y += 6 }); y += 16

  const stats = [
    { n: String(blueprint.users?.length || 0), l: 'Users' },
    { n: String(blueprint.feature_breakdown?.length || 0), l: 'Features' },
    { n: String(blueprint.services?.length || 0), l: 'Services' },
    { n: String(blueprint.integrations?.length || 0), l: 'Integrations' },
    { n: String(blueprint.domain_entities?.length || 0), l: 'Entities' },
    { n: String(blueprint.business_goals?.length || 0), l: 'Goals' },
  ]
  const sw = CW / 6
  stats.forEach((s, i) => {
    const sx = M + i * sw
    strokeRect(sx, y, sw - 2, 18, BG2, RULE, 2)
    sf(16, 'bold', INK); tx(s.n, sx + (sw - 2) / 2, y + 9, { align: 'center' } as any)
    sf(7, 'normal', INK4); tx(s.l.toUpperCase(), sx + (sw - 2) / 2, y + 14.5, { align: 'center' } as any)
  }); y += 26

  hline(y); y += 8
  const meta = [{ l: 'Date', v: dateStr }, { l: 'Version', v: '1.0' }, { l: 'Status', v: 'Draft' }, { l: 'Generated by', v: 'cornea.ai' }]
  meta.forEach((m, i) => {
    const mx = M + i * (CW / 4)
    sf(7, 'bold', INK4); tx(m.l.toUpperCase(), mx, y)
    sf(10, 'bold', INK2); tx(m.v, mx, y + 6)
  })

  // ── SECTION PAGES ─────────────────────────────────────────────────
  addPage()

  // 1. Executive Summary
  secHeader('1', 'Executive Summary')
  const sumLines = doc.splitTextToSize(blueprint.prd_summary || '', CW - 10)
  const sumH = sumLines.length * 5.5 + 10
  checkY(sumH)
  strokeRect(M, y - 2, CW, sumH, '#eff6ff', '#bfdbfe', 2)
  fillRect(M, y - 2, 2, sumH, BLUE, 1)
  sf(10, 'normal', '#1e3a8a')
  sumLines.forEach((l: string, i: number) => tx(l, M + 6, y + 4 + i * 5.5))
  y += sumH + 8
  sf(10, 'normal', INK2)
  const expLines = doc.splitTextToSize(blueprint.system_explanation || '', CW)
  expLines.forEach((l: string) => { checkY(6); tx(l, M, y); y += 5.5 }); y += 10

  // 2. Problem Statement
  checkY(20); secHeader('2', 'Problem Statement')
  const probH = 14; strokeRect(M, y - 2, CW, probH, '#fffbeb', '#fde68a', 2)
  fillRect(M, y - 2, 2, probH, AMBER, 1)
  sf(10, 'normal', '#78350f'); tx('The following pain points define the core opportunity this product addresses.', M + 6, y + 5)
  y += probH + 6
  ;(blueprint.business_goals || []).slice(0, 4).forEach((g, i) => {
    checkY(10); strokeRect(M, y - 2, CW, 9, BG2, RULE, 1.5)
    sf(8, 'bold', BLUE); tx(`P${String(i + 1).padStart(2, '0')}`, M + 3, y + 3.5)
    sf(10, 'normal', INK2); tx(doc.splitTextToSize(g, CW - 18)[0], M + 13, y + 3.5); y += 11
  }); y += 8

  // 3. Goals
  checkY(20); secHeader('3', 'Goals & Success Metrics')
  ;(blueprint.business_goals || []).forEach((g, i) => {
    checkY(10); strokeRect(M, y - 2, CW, 9, BG2, RULE, 1.5)
    sf(8, 'bold', BLUE); tx(`G${String(i + 1).padStart(2, '0')}`, M + 3, y + 3.5)
    sf(10, 'normal', INK2); tx(doc.splitTextToSize(g, CW - 18)[0], M + 13, y + 3.5); y += 11
  }); y += 8

  // 4. Personas
  checkY(20); secHeader('4', 'User Personas')
  ;(blueprint.users || []).forEach((u, i) => {
    const dl = doc.splitTextToSize(u.description || '', CW - 36)
    const ch = Math.max(22, dl.length * 4.5 + 14)
    checkY(ch + 4)
    strokeRect(M, y, CW, ch, i % 2 === 0 ? '#eff6ff' : BG2, RULE, 2)
    doc.setFillColor(BLUE + '33'); doc.circle(M + 10, y + ch / 2, 6, 'F')
    sf(10, 'bold', INK); tx(u.name, M + 20, y + 8)
    sf(8, 'bold', BLUE); tx(u.role.toUpperCase(), M + 20, y + 13.5)
    sf(9, 'normal', INK3); dl.forEach((l: string, li: number) => tx(l, M + 20, y + 19 + li * 4.5))
    y += ch + 4
  }); y += 6

  // 5. Functional Requirements
  checkY(20); secHeader('5', 'Functional Requirements')
  fillRect(M, y - 2, CW, 8, '#f3f4f6', 1.5)
  sf(7, 'bold', INK3)
  tx('ID', M + 2, y + 3); tx('FEATURE', M + 20, y + 3); tx('DESCRIPTION', M + 60, y + 3); tx('PRIORITY', M + 135, y + 3); tx('SERVICE', M + 162, y + 3)
  y += 10
  ;(blueprint.feature_breakdown || []).forEach((f, i) => {
    const dl = doc.splitTextToSize(f.description || '', 70)
    const rh = Math.max(10, dl.length * 4.5 + 5)
    checkY(rh + 2)
    if (i % 2 === 0) { doc.setFillColor(BG2); doc.rect(M, y - 2, CW, rh + 2, 'F') }
    hline(y + rh, '#f0f0f0')
    sf(8, 'bold', BLUE); tx(`FR-${String(i + 1).padStart(3, '0')}`, M + 2, y + 4)
    sf(9, 'bold', INK); tx(doc.splitTextToSize(f.feature, 36)[0], M + 20, y + 4)
    sf(9, 'normal', INK2); dl.forEach((l: string, li: number) => tx(l, M + 60, y + 4 + li * 4.5))
    badgeTag(f.badge || 'Core', M + 135, y + 4, BADGE_COLORS[f.badge] || BLUE)
    sf(8, 'normal', INK4); tx(doc.splitTextToSize(f.service, 42)[0], M + 162, y + 4)
    y += rh + 2
  }); y += 10

  // 6. NFRs
  checkY(20); secHeader('6', 'Non-Functional Requirements')
  const nfrs = [
    { id: 'NFR-001', cat: 'Performance', req: 'API response time <= 500ms at 95th percentile.' },
    { id: 'NFR-002', cat: 'Scalability', req: 'Horizontal scaling to 10x baseline without architecture changes.' },
    { id: 'NFR-003', cat: 'Security', req: 'TLS 1.3 in transit. AES-256 at rest for sensitive data.' },
    { id: 'NFR-004', cat: 'Availability', req: '99.9% uptime SLA excluding scheduled maintenance.' },
    { id: 'NFR-005', cat: 'Maintainability', req: 'Test coverage > 80%. OpenAPI docs for all public APIs.' },
    { id: 'NFR-006', cat: 'Accessibility', req: 'WCAG 2.1 Level AA across all user-facing interfaces.' },
  ]
  nfrs.forEach((r, i) => {
    checkY(10)
    if (i % 2 === 0) { doc.setFillColor(BG2); doc.rect(M, y - 2, CW, 9, 'F') }
    hline(y + 7, '#f0f0f0')
    sf(8, 'bold', BLUE); tx(r.id, M + 2, y + 3.5)
    sf(9, 'bold', INK); tx(r.cat, M + 22, y + 3.5)
    sf(9, 'normal', INK2); tx(r.req, M + 55, y + 3.5); y += 9
  }); y += 10

  // 7. Architecture
  checkY(20); secHeader('7', 'System Architecture')
  sf(10, 'normal', INK2)
  doc.splitTextToSize(blueprint.system_explanation || '', CW).slice(0, 2).forEach((l: string) => { checkY(6); tx(l, M, y); y += 5.5 }); y += 8
  ;(blueprint.services || []).forEach(s => {
    const dl = doc.splitTextToSize(s.description || '', CW - 8)
    const ac = (s.apis || []).length
    const ch = dl.length * 4.5 + ac * 7.5 + 22
    checkY(ch + 4)
    strokeRect(M, y, CW, ch, '#faf5ff', '#e9d5ff', 2)
    fillRect(M, y, CW, 11, '#f3e8ff', 2)
    doc.setFillColor('#f3e8ff'); doc.rect(M, y + 6, CW, 5, 'F')
    sf(10, 'bold', PURPLE); tx(s.name, M + 4, y + 8)
    sf(7, 'bold', PURPLE); tx(s.group.toUpperCase(), W - M - 4, y + 8, { align: 'right' } as any)
    y += 14
    sf(9, 'normal', INK3); dl.forEach((l: string) => { tx(l, M + 4, y); y += 4.5 }); y += 3
    ;(s.apis || []).forEach(a => {
      const mc = METHOD_COLORS[a.method] || BLUE
      doc.setFillColor(mc + '18'); doc.roundedRect(M + 4, y - 2, CW - 8, 7, 1, 1, 'F')
      sf(8, 'bold', mc); tx(a.method, M + 7, y + 3)
      sf(8, 'normal', INK); tx(a.route, M + 22, y + 3)
      sf(8, 'normal', INK4); tx(`— ${a.purpose}`, M + 22 + doc.getTextWidth(a.route) + 3, y + 3); y += 7.5
    }); y += 6
  }); y += 4

  // 8. Data
  checkY(20); secHeader('8', 'Data Architecture')
  const di = [
    { l: 'Primary Database', v: blueprint.data_layer?.database },
    { l: 'Cache Layer', v: blueprint.data_layer?.cache },
    { l: 'File Storage', v: blueprint.data_layer?.storage },
  ].filter(d => d.v)
  if (di.length > 0) {
    const dw2 = CW / di.length - 3
    di.forEach((d, i) => {
      const dx = M + i * (dw2 + 3)
      strokeRect(dx, y, dw2, 16, '#ecfdf5', '#a7f3d0', 2)
      sf(13, 'bold', GREEN); tx(d.v!, dx + dw2 / 2, y + 9, { align: 'center' } as any)
      sf(7, 'bold', INK4); tx(d.l.toUpperCase(), dx + dw2 / 2, y + 14, { align: 'center' } as any)
    }); y += 22
  }
  sf(10, 'normal', INK2)
  doc.splitTextToSize(blueprint.data_layer?.description || '', CW).forEach((l: string) => { checkY(6); tx(l, M, y); y += 5.5 }); y += 8
  sf(11, 'bold', INK); tx('Domain Entities', M, y); y += 8
  ;(blueprint.domain_entities || []).forEach(e => {
    const el = doc.splitTextToSize(e.description || '', CW - 8)
    const fieldRows = Math.ceil((e.fields || []).length / 5)
    const ch = el.length * 4.5 + fieldRows * 7 + 16
    checkY(ch + 4)
    strokeRect(M, y, CW, ch, '#ecfdf5', '#a7f3d0', 2)
    fillRect(M, y, CW, 9, '#d1fae5', 2); doc.setFillColor('#d1fae5'); doc.rect(M, y + 5, CW, 4, 'F')
    sf(10, 'bold', GREEN); tx(e.name, M + 4, y + 6.5); y += 12
    sf(9, 'normal', INK3); el.forEach((l: string) => { tx(l, M + 4, y); y += 4.5 }); y += 3
    let fx = M + 4
    ;(e.fields || []).forEach(field => {
      const fw = doc.getTextWidth(field) + 8
      if (fx + fw > W - M) { fx = M + 4; y += 7 }
      strokeRect(fx, y - 3, fw, 6, '#f3f4f6', RULE, 1)
      sf(8, 'normal', INK2); tx(field, fx + 4, y + 1.5); fx += fw + 3
    }); y += 10
  }); y += 6

  // 9. Integrations
  checkY(20); secHeader('9', 'External Integrations')
  ;(blueprint.integrations || []).forEach((int, i) => {
    checkY(20); const iw = CW / 2 - 2; const ix = M + (i % 2) * (iw + 4)
    if (i % 2 === 0) {
      strokeRect(ix, y, iw, 20, BG2, RULE, 2)
      if (blueprint.integrations?.[i + 1]) strokeRect(M + iw + 4, y, iw, 20, BG2, RULE, 2)
    }
    doc.setFillColor('#f5f3ff'); doc.circle(ix + 8, y + 10, 5, 'F')
    sf(10, 'bold', INK); tx(int.name, ix + 16, y + 8)
    sf(8, 'normal', INK3); tx(doc.splitTextToSize(int.purpose, iw - 18)[0], ix + 16, y + 13)
    sf(7, 'bold', PURPLE); tx(int.type.toUpperCase(), ix + 16, y + 18)
    if (i % 2 === 1) y += 23
  })
  if ((blueprint.integrations || []).length % 2 !== 0) y += 23; y += 6

  // 10. Business Rules
  checkY(20); secHeader('10', 'Business Rules & Constraints')
  ;(blueprint.business_rules || []).forEach((r, i) => {
    const rl = doc.splitTextToSize(r, CW - 20); const rh = rl.length * 4.5 + 6
    checkY(rh + 2)
    if (i % 2 === 0) { doc.setFillColor(BG2); doc.rect(M, y - 2, CW, rh + 2, 'F') }
    hline(y + rh, '#f0f0f0')
    sf(8, 'bold', BLUE); tx(`BR-${String(i + 1).padStart(3, '0')}`, M + 2, y + 4)
    sf(9, 'normal', INK2); rl.forEach((l: string, li: number) => tx(l, M + 20, y + 4 + li * 4.5)); y += rh + 2
  }); y += 10

  // 11. Out of Scope
  checkY(20); secHeader('11', 'Out of Scope — Version 1.0')
  const oos = ['Native mobile applications (web-responsive only)', 'Third-party plugin or marketplace system', 'Multi-language / i18n support', 'Advanced AI/ML beyond core scope', 'Custom on-premise deployment']
  oos.forEach(item => {
    checkY(10); strokeRect(M, y - 2, CW, 9, '#fef2f2', '#fecaca', 1.5)
    sf(10, 'bold', RED); tx('-', M + 3, y + 3.5); sf(9, 'normal', RED); tx(item, M + 10, y + 3.5); y += 11
  }); y += 8

  // 12. Assumptions
  checkY(20); secHeader('12', 'Assumptions & Dependencies')
  const assumptions = (blueprint.system_boundaries || []).length > 0 ? blueprint.system_boundaries
    : ['Users access via a modern web browser.', 'Third-party APIs maintain backward compatibility during development.', 'Infrastructure provisioned on a major cloud provider.', 'Development follows standard agile practices.', 'Legal review completed before production launch.']
  assumptions.forEach((a, i) => {
    const al = doc.splitTextToSize(a, CW - 18); const ah = al.length * 4.5 + 6
    checkY(ah + 2)
    if (i % 2 === 0) { doc.setFillColor(BG2); doc.rect(M, y - 2, CW, ah + 2, 'F') }
    hline(y + ah, '#f0f0f0')
    sf(8, 'bold', BLUE); tx(`A${String(i + 1).padStart(2, '0')}`, M + 2, y + 4)
    sf(9, 'normal', INK2); al.forEach((l: string, li: number) => tx(l, M + 14, y + 4 + li * 4.5)); y += ah + 2
  })

  // Footer on every page
  const total = (doc as any).internal.getNumberOfPages()
  for (let p = 1; p <= total; p++) {
    doc.setPage(p)
    hline(285)
    sf(8, 'normal', INK4)
    tx('Generated by cornea.ai', M, 290)
    tx('Version 1.0 · CONFIDENTIAL', W / 2, 290, { align: 'center' } as any)
    tx(`${p} / ${total}`, W - M, 290, { align: 'right' } as any)
  }

  doc.save(`prd-${idea.slice(0, 30).replace(/\s+/g, '-').toLowerCase()}.pdf`)
}